/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.ControladorProductoFresco;
import javax.swing.JOptionPane;
import modelos.ProductoFresco;

/**
 *
 * @author carol
 */
public class VenatanaModificarPF extends javax.swing.JInternalFrame {

    /**
     * Creates new form VenatanaModificarPF
     */
    private final String[] carne = {"Selecciona", "Ternera", "Res", "Puerco", "Cordero", "Lechon"};
    private final String[] lacteo = {"Selecciona", "Leche", "Mantequilla", "Queso", "Yogurt"};
    private final String[] marisco = {"Selcciona", "Mero", "Atun", "Bacalao", "Carpa", "Salmon", "Trucha", "Sardina"};
    private final String[] fruta = {"Selecciona", "Manzana", "Platano", "Pera", "Naranja"};
    private final String[] verdura = {"Selecciona", "Lechuga", "Apio", "Repollo", "Zanahoria", "Cebolla"};
    private final String[] panaderia = {"Selecciona", "Pan frances", "Pan de centeno", "Bagels", "Croissant"};

    private ControladorProductoFresco controlador = new ControladorProductoFresco();

    public VenatanaModificarPF() {
        initComponents();
        agregarCantidad();
        agregarNumGrados();
        agregarFecha();
    }

    private void agregarCantidad() {
        for (int i = 1; i <= 100; i++) {
            this.cbxCantidadPFM.addItem(Integer.toString(i));
        }
    }

    private void agregarNumGrados() {
        for (int i = -10; i <= 10; i++) {
            this.cbxNumeroGPFM.addItem(Integer.toString(i));
        }

        this.cbxNumeroGPFM.setSelectedItem("0");
    }

    private void agregarFecha() {
        for (int i = 1; i <= 31; i++) {
            this.cbxDiaPFM.addItem(Integer.toString(i));
        }
        for (int i = 2021; i < 2050; i++) {
            this.cbxAnioPFM.addItem(Integer.toString(i));
        }
    }

    private void limpiarObjetos() {
        this.tfClavePFM.setText("");
        this.cbxdescripcionPFM.setSelectedIndex(0);
        this.cbxCantidadPFM.setSelectedIndex(0);
        this.tfNoLotePFM.setText("");
        this.cbxDiaPFM.setSelectedIndex(0);
        this.cbxMesPFM.setSelectedIndex(0);
        this.cbxAnioPFM.setSelectedIndex(0);
        this.cbxNumeroGPFM.setSelectedItem("0");
        this.cbxTipoGPFM.setSelectedIndex(0);
        this.cbxTipoPFM.removeAllItems();
        this.cbxTipoPFM.addItem("Selecciona");
    }

    private void habilitarCampos() {
        this.cbxdescripcionPFM.setEnabled(true);
        this.cbxCantidadPFM.setEnabled(true);
        this.tfNoLotePFM.setEnabled(true);
        this.cbxDiaPFM.setEnabled(true);
        this.cbxMesPFM.setEnabled(true);
        this.cbxAnioPFM.setEnabled(true);
        this.cbxNumeroGPFM.setEnabled(true);
        this.cbxTipoGPFM.setEnabled(true);
        this.cbxTipoPFM.setEnabled(true);
        
        this.btnGuardarPFM.setEnabled(true);
        this.btnCancelarPFM.setEnabled(true);
    }

    private void desactivarCampos() {
        this.cbxdescripcionPFM.setEnabled(false);
        this.cbxCantidadPFM.setEnabled(false);
        this.tfNoLotePFM.setEnabled(false);
        this.cbxDiaPFM.setEnabled(false);
        this.cbxMesPFM.setEnabled(false);
        this.cbxAnioPFM.setEnabled(false);
        this.cbxNumeroGPFM.setEnabled(false);
        this.cbxTipoGPFM.setEnabled(false);
        this.cbxTipoPFM.setEnabled(false);
        this.btnGuardarPFM.setEnabled(false);
        this.btnCancelarPFM.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxTipoGPFM = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxTipoPFM = new javax.swing.JComboBox<>();
        cbxdescripcionPFM = new javax.swing.JComboBox<>();
        btnGuardarPFM = new javax.swing.JButton();
        btnCancelarPFM = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfNoLotePFM = new javax.swing.JTextField();
        tfClavePFM = new javax.swing.JTextField();
        cbxCantidadPFM = new javax.swing.JComboBox<>();
        cbxDiaPFM = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxMesPFM = new javax.swing.JComboBox<>();
        cbxNumeroGPFM = new javax.swing.JComboBox<>();
        cbxAnioPFM = new javax.swing.JComboBox<>();
        btnBuscarPF = new javax.swing.JButton();

        setClosable(true);
        setTitle("Modificar producto fresco");

        cbxTipoGPFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));
        cbxTipoGPFM.setEnabled(false);

        jLabel6.setText("Cantidad");

        cbxTipoPFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        cbxTipoPFM.setEnabled(false);

        cbxdescripcionPFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Marisco", "Carne", "Fruta", "Verdura", "Panaderia", "Lacteos" }));
        cbxdescripcionPFM.setEnabled(false);
        cbxdescripcionPFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxdescripcionPFMActionPerformed(evt);
            }
        });

        btnGuardarPFM.setText("Guardar");
        btnGuardarPFM.setEnabled(false);
        btnGuardarPFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPFMActionPerformed(evt);
            }
        });

        btnCancelarPFM.setText("Cancelar");
        btnCancelarPFM.setEnabled(false);
        btnCancelarPFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPFMActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Clave");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("No. Lote");

        jLabel1.setText("Fecha de caducidad");

        tfNoLotePFM.setEnabled(false);
        tfNoLotePFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoLotePFMActionPerformed(evt);
            }
        });

        cbxCantidadPFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        cbxCantidadPFM.setEnabled(false);
        cbxCantidadPFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantidadPFMActionPerformed(evt);
            }
        });

        cbxDiaPFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día" }));
        cbxDiaPFM.setEnabled(false);

        jLabel3.setText("Temperatura recomendada");

        jLabel5.setText("Descripcion");

        jLabel7.setText("Tipo");

        cbxMesPFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbxMesPFM.setEnabled(false);
        cbxMesPFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesPFMActionPerformed(evt);
            }
        });

        cbxNumeroGPFM.setEnabled(false);

        cbxAnioPFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        cbxAnioPFM.setEnabled(false);

        btnBuscarPF.setText("Buscar");
        btnBuscarPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbxNumeroGPFM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbxTipoGPFM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxTipoPFM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btnCancelarPFM)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnGuardarPFM))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbxDiaPFM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxMesPFM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxAnioPFM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfClavePFM, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(84, 84, 84)
                                    .addComponent(btnBuscarPF))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbxCantidadPFM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfNoLotePFM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(50, 50, 50)))
                    .addComponent(cbxdescripcionPFM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfClavePFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxdescripcionPFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxCantidadPFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNoLotePFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMesPFM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbxDiaPFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxAnioPFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxNumeroGPFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoGPFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxTipoPFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPFM)
                    .addComponent(btnCancelarPFM))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxdescripcionPFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxdescripcionPFMActionPerformed
        switch (this.cbxdescripcionPFM.getSelectedIndex()) {
            case 1:
                this.cbxTipoPFM.removeAllItems();
                for (String item : marisco) {
                    this.cbxTipoPFM.addItem(item);
                }
                break;
            case 2:
                this.cbxTipoPFM.removeAllItems();
                for (String item : carne) {
                    this.cbxTipoPFM.addItem(item);
                }
                break;
            case 3:
                this.cbxTipoPFM.removeAllItems();
                for (String item : fruta) {
                    this.cbxTipoPFM.addItem(item);
                }
                break;
            case 4:
                this.cbxTipoPFM.removeAllItems();
                for (String item : verdura) {
                    this.cbxTipoPFM.addItem(item);
                }
                break;
            case 5:
                this.cbxTipoPFM.removeAllItems();
                for (String item : panaderia) {
                    this.cbxTipoPFM.addItem(item);
                }
                break;
            case 6:
                this.cbxTipoPFM.removeAllItems();
                for (String item : lacteo) {
                    this.cbxTipoPFM.addItem(item);
                }
                break;
        }
    }//GEN-LAST:event_cbxdescripcionPFMActionPerformed

    private void btnGuardarPFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPFMActionPerformed
        ProductoFresco nuevoProducto = new ProductoFresco();
        controlador = new ControladorProductoFresco();
        if (this.cbxdescripcionPFM.getSelectedIndex() != 0) {

            if (this.cbxCantidadPFM.getSelectedIndex() != 0) {

                if (!this.tfNoLotePFM.getText().equals("")) {

                    if (this.cbxDiaPFM.getSelectedIndex() != 0 || this.cbxMesPFM.getSelectedIndex() != 0 || this.cbxAnioPFM.getSelectedIndex() != 0) {

                        if (this.cbxTipoPFM.getSelectedIndex() != 0) {

                            nuevoProducto.setClave(this.tfClavePFM.getText());
                            nuevoProducto.setCantidad(Integer.parseInt(this.cbxCantidadPFM.getItemAt(this.cbxCantidadPFM.getSelectedIndex())));
                            nuevoProducto.setDescripcion(this.cbxdescripcionPFM.getItemAt(this.cbxdescripcionPFM.getSelectedIndex()));

                            String fecha = this.cbxDiaPFM.getItemAt(this.cbxDiaPFM.getSelectedIndex()) + "/"
                                    + this.cbxMesPFM.getSelectedIndex() + "/"
                                    + this.cbxAnioPFM.getItemAt(this.cbxAnioPFM.getSelectedIndex());

                            nuevoProducto.setFechaCaducidad(fecha);

                            String temp = this.cbxNumeroGPFM.getItemAt(this.cbxNumeroGPFM.getSelectedIndex()) + "/"
                                    + this.cbxTipoGPFM.getItemAt(this.cbxTipoGPFM.getSelectedIndex());

                            nuevoProducto.setTemperaturaRecomendada(temp);

                            nuevoProducto.setTipoAlimento(this.cbxTipoPFM.getItemAt(this.cbxTipoPFM.getSelectedIndex()));
                            nuevoProducto.setNumeroLote(this.tfNoLotePFM.getText());

                            limpiarObjetos();
                            desactivarCampos();
                            controlador.modificarProducto(nuevoProducto);
                        } else {
                            JOptionPane.showMessageDialog(null, "El producto debe de tener un tipo de alimento.");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Ingresa una fecha valida.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El producto debe de tener un número de lote.");
                }

            } else {
                JOptionPane.showMessageDialog(null, "La cantidad del producto debe de ser mayor a cero.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Es necesario seleccionar una descripcion\ndel producto.");
        }
    }//GEN-LAST:event_btnGuardarPFMActionPerformed

    private void btnCancelarPFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPFMActionPerformed
        limpiarObjetos();
        this.desactivarCampos();
        JOptionPane.showMessageDialog(null, "Operacion cancelada", "Modificar productos frescos", 2);
        this.dispose();
    }//GEN-LAST:event_btnCancelarPFMActionPerformed

    private void tfNoLotePFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoLotePFMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoLotePFMActionPerformed

    private void cbxCantidadPFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantidadPFMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCantidadPFMActionPerformed

    private void cbxMesPFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesPFMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesPFMActionPerformed

    private void btnBuscarPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPFActionPerformed
        if (!this.tfClavePFM.getText().equals("")) {

            if (this.controlador.validarClave(this.tfClavePFM.getText())) {

                ProductoFresco producto = this.controlador.buscarProducto(this.tfClavePFM.getText());
                habilitarCampos();

                this.cbxdescripcionPFM.setSelectedItem(producto.getDescripcion());
                this.cbxCantidadPFM.setSelectedIndex(producto.getCantidad());

                String[] fecha = producto.getFechaCaducidad().split("/");
                this.cbxDiaPFM.setSelectedItem(fecha[0]);
                this.cbxMesPFM.setSelectedIndex(Integer.parseInt(fecha[1]));
                this.cbxAnioPFM.setSelectedItem(fecha[2]);

                String[] temperatura = producto.getTemperaturaRecomendada().split("/");
                this.cbxNumeroGPFM.setSelectedItem(temperatura[0]);
                this.cbxTipoGPFM.setSelectedItem(temperatura[1]);

                this.cbxTipoPFM.setSelectedItem(producto.getTipoAlimento());
                this.tfNoLotePFM.setText(producto.getNumeroLote());

            } else {
                JOptionPane.showMessageDialog(null, "No se encontro ningun producto con esa clave");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Se necesita una clave par abuscar.");
        }
    }//GEN-LAST:event_btnBuscarPFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPF;
    private javax.swing.JButton btnCancelarPFM;
    private javax.swing.JButton btnGuardarPFM;
    private javax.swing.JComboBox<String> cbxAnioPFM;
    private javax.swing.JComboBox<String> cbxCantidadPFM;
    private javax.swing.JComboBox<String> cbxDiaPFM;
    private javax.swing.JComboBox<String> cbxMesPFM;
    private javax.swing.JComboBox<String> cbxNumeroGPFM;
    private javax.swing.JComboBox<String> cbxTipoGPFM;
    private javax.swing.JComboBox<String> cbxTipoPFM;
    private javax.swing.JComboBox<String> cbxdescripcionPFM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfClavePFM;
    private javax.swing.JTextField tfNoLotePFM;
    // End of variables declaration//GEN-END:variables
}
