/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.modificarP;

import controlador.ControladorProductoRefrigerado;
import javax.swing.JOptionPane;
import modelos.ProductoRefrigerado;

/**
 *
 * @author carol
 */
public class VentanaModificarPR extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaModificarPR
     */
    
    private ControladorProductoRefrigerado controlador = new ControladorProductoRefrigerado();
    
    
    public VentanaModificarPR() {
        initComponents();
        agregarCantidad();
        agregarNumGrados();
        agregarFecha();
    }
    
    private void agregarCantidad() {
        for (int i = 1; i <= 100; i++) {
            this.cbxCantidadPRM.addItem(Integer.toString(i));
        }
    }

    private void agregarNumGrados() {
        for (int i = -10; i <= 10; i++) {
            this.cbxNumeroGPRM.addItem(Integer.toString(i));
        }

        this.cbxNumeroGPRM.setSelectedItem("0");
    }

    private void agregarFecha() {
        for (int i = 1; i <= 31; i++) {
            this.cbxDiaPRM.addItem(Integer.toString(i));
        }
        for (int i = 2021; i < 2050; i++) {
            this.cbxAnioPRM.addItem(Integer.toString(i));
        }
    }

    private void limpiarObjetos() {
        this.tfClavePRM.setText("");
        this.cbxdescripcionPRM.setSelectedIndex(0);
        this.cbxCantidadPRM.setSelectedIndex(0);
        this.tfNoLotePRM.setText("");
        this.cbxDiaPRM.setSelectedIndex(0);
        this.cbxMesPRM.setSelectedIndex(0);
        this.cbxAnioPRM.setSelectedIndex(0);
        this.cbxNumeroGPRM.setSelectedItem("0");
        this.cbxTipoGPRM.setSelectedIndex(0);
        this.cbxTipoPRM.removeAllItems();
        this.cbxTipoPRM.addItem("Selecciona");
    }

    private void habilitarCampos() {
        this.cbxdescripcionPRM.setEnabled(true);
        this.cbxCantidadPRM.setEnabled(true);
        this.tfNoLotePRM.setEnabled(true);
        this.cbxDiaPRM.setEnabled(true);
        this.cbxMesPRM.setEnabled(true);
        this.cbxAnioPRM.setEnabled(true);
        this.cbxNumeroGPRM.setEnabled(true);
        this.cbxTipoGPRM.setEnabled(true);
        this.cbxTipoPRM.setEnabled(true);
        
        this.btnGuardarPRM.setEnabled(true);
        this.btnCancelarPRM.setEnabled(true);
    }

    private void desactivarCampos() {
        this.cbxdescripcionPRM.setEnabled(false);
        this.cbxCantidadPRM.setEnabled(false);
        this.tfNoLotePRM.setEnabled(false);
        this.cbxDiaPRM.setEnabled(false);
        this.cbxMesPRM.setEnabled(false);
        this.cbxAnioPRM.setEnabled(false);
        this.cbxNumeroGPRM.setEnabled(false);
        this.cbxTipoGPRM.setEnabled(false);
        this.cbxTipoPRM.setEnabled(false);
        this.btnGuardarPRM.setEnabled(false);
        this.btnCancelarPRM.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxTipoGPRM = new javax.swing.JComboBox<>();
        cbxCantidadPRM = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxDiaPRM = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxMesPRM = new javax.swing.JComboBox<>();
        cbxNumeroGPRM = new javax.swing.JComboBox<>();
        cbxTipoPRM = new javax.swing.JComboBox<>();
        cbxAnioPRM = new javax.swing.JComboBox<>();
        cbxdescripcionPRM = new javax.swing.JComboBox<>();
        btnBuscarPR = new javax.swing.JButton();
        btnGuardarPRM = new javax.swing.JButton();
        btnCancelarPRM = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfNoLotePRM = new javax.swing.JTextField();
        tfClavePRM = new javax.swing.JTextField();

        setTitle("Modificar producto refrigerado");

        cbxTipoGPRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));
        cbxTipoGPRM.setEnabled(false);

        cbxCantidadPRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        cbxCantidadPRM.setEnabled(false);
        cbxCantidadPRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantidadPRMActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad");

        cbxDiaPRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día" }));
        cbxDiaPRM.setEnabled(false);

        jLabel3.setText("Temperatura recomendada");

        jLabel5.setText("Descripcion");

        jLabel7.setText("Tipo");

        cbxMesPRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbxMesPRM.setEnabled(false);
        cbxMesPRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesPRMActionPerformed(evt);
            }
        });

        cbxNumeroGPRM.setEnabled(false);

        cbxTipoPRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Fisico", "Quimico", "Biologicos", "Microbiologicos" }));
        cbxTipoPRM.setEnabled(false);

        cbxAnioPRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        cbxAnioPRM.setEnabled(false);

        cbxdescripcionPRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Marisco", "Carne", "Fruta", "Verdura", "Panaderia", "Lacteos" }));
        cbxdescripcionPRM.setEnabled(false);
        cbxdescripcionPRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxdescripcionPRMActionPerformed(evt);
            }
        });

        btnBuscarPR.setText("Buscar");
        btnBuscarPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPRActionPerformed(evt);
            }
        });

        btnGuardarPRM.setText("Guardar");
        btnGuardarPRM.setEnabled(false);
        btnGuardarPRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPRMActionPerformed(evt);
            }
        });

        btnCancelarPRM.setText("Cancelar");
        btnCancelarPRM.setEnabled(false);
        btnCancelarPRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPRMActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Clave");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("No. Lote");

        jLabel1.setText("Fecha de caducidad");

        tfNoLotePRM.setEnabled(false);
        tfNoLotePRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoLotePRMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbxNumeroGPRM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbxTipoGPRM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxTipoPRM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btnCancelarPRM)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnGuardarPRM))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbxDiaPRM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxMesPRM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxAnioPRM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfClavePRM, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(84, 84, 84)
                                    .addComponent(btnBuscarPR))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbxCantidadPRM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfNoLotePRM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(50, 50, 50)))
                    .addComponent(cbxdescripcionPRM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfClavePRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxdescripcionPRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxCantidadPRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNoLotePRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMesPRM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbxDiaPRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxAnioPRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxNumeroGPRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoGPRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxTipoPRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPRM)
                    .addComponent(btnCancelarPRM))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCantidadPRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantidadPRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCantidadPRMActionPerformed

    private void cbxMesPRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesPRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesPRMActionPerformed

    private void cbxdescripcionPRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxdescripcionPRMActionPerformed
        
    }//GEN-LAST:event_cbxdescripcionPRMActionPerformed

    private void btnBuscarPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPRActionPerformed
        if (!this.tfClavePRM.getText().equals("")) {

            if (this.controlador.validarClave(this.tfClavePRM.getText())) {

                ProductoRefrigerado producto = this.controlador.buscarProducto(this.tfClavePRM.getText());
                habilitarCampos();

                this.cbxdescripcionPRM.setSelectedItem(producto.getDescripcion());
                this.cbxCantidadPRM.setSelectedIndex(producto.getCantidad());

                String[] fecha = producto.getFechaCaducidad().split("/");
                this.cbxDiaPRM.setSelectedItem(fecha[0]);
                this.cbxMesPRM.setSelectedIndex(Integer.parseInt(fecha[1]));
                this.cbxAnioPRM.setSelectedItem(fecha[2]);

                String[] temperatura = producto.getTemperaturaRecomendada().split("/");
                this.cbxNumeroGPRM.setSelectedItem(temperatura[0]);
                this.cbxTipoGPRM.setSelectedItem(temperatura[1]);

                this.cbxTipoPRM.setSelectedItem(producto.getTipoContaminacion());
                this.tfNoLotePRM.setText(producto.getNumeroLote());

            } else {
                JOptionPane.showMessageDialog(null, "No se encontro ningun producto con esa clave");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Se necesita una clave par abuscar.");
        }
    }//GEN-LAST:event_btnBuscarPRActionPerformed

    private void btnGuardarPRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPRMActionPerformed
        ProductoRefrigerado nuevoProducto = new ProductoRefrigerado();
        controlador = new ControladorProductoRefrigerado();
        if (this.cbxdescripcionPRM.getSelectedIndex() != 0) {

            if (this.cbxCantidadPRM.getSelectedIndex() != 0) {

                if (!this.tfNoLotePRM.getText().equals("")) {

                    if (this.cbxDiaPRM.getSelectedIndex() != 0 || this.cbxMesPRM.getSelectedIndex() != 0 || this.cbxAnioPRM.getSelectedIndex() != 0) {

                        if (this.cbxTipoPRM.getSelectedIndex() != 0) {

                            nuevoProducto.setClave(this.tfClavePRM.getText());
                            nuevoProducto.setCantidad(Integer.parseInt(this.cbxCantidadPRM.getItemAt(this.cbxCantidadPRM.getSelectedIndex())));
                            nuevoProducto.setDescripcion(this.cbxdescripcionPRM.getItemAt(this.cbxdescripcionPRM.getSelectedIndex()));

                            String fecha = this.cbxDiaPRM.getItemAt(this.cbxDiaPRM.getSelectedIndex()) + "/"
                            + this.cbxMesPRM.getSelectedIndex() + "/"
                            + this.cbxAnioPRM.getItemAt(this.cbxAnioPRM.getSelectedIndex());

                            nuevoProducto.setFechaCaducidad(fecha);

                            String temp = this.cbxNumeroGPRM.getItemAt(this.cbxNumeroGPRM.getSelectedIndex()) + "/"
                            + this.cbxTipoGPRM.getItemAt(this.cbxTipoGPRM.getSelectedIndex());

                            nuevoProducto.setTemperaturaRecomendada(temp);

                            nuevoProducto.setTipoContaminacion(this.cbxTipoPRM.getItemAt(this.cbxTipoPRM.getSelectedIndex()));
                            nuevoProducto.setNumeroLote(this.tfNoLotePRM.getText());

                            limpiarObjetos();
                            desactivarCampos();
                            controlador.modificarProducto(nuevoProducto);
                        } else {
                            JOptionPane.showMessageDialog(null, "El producto debe de tener un tipo de alimento.");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Ingresa una fecha valida.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El producto debe de tener un número de lote.");
                }

            } else {
                JOptionPane.showMessageDialog(null, "La cantidad del producto debe de ser mayor a cero.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Es necesario seleccionar una descripcion\ndel producto.");
        }
    }//GEN-LAST:event_btnGuardarPRMActionPerformed

    private void btnCancelarPRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPRMActionPerformed
        limpiarObjetos();
        this.desactivarCampos();
        JOptionPane.showMessageDialog(null, "Operacion cancelada", "Modificar productos refrigerados", 2);
        this.dispose();
    }//GEN-LAST:event_btnCancelarPRMActionPerformed

    private void tfNoLotePRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoLotePRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoLotePRMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPR;
    private javax.swing.JButton btnCancelarPRM;
    private javax.swing.JButton btnGuardarPRM;
    private javax.swing.JComboBox<String> cbxAnioPRM;
    private javax.swing.JComboBox<String> cbxCantidadPRM;
    private javax.swing.JComboBox<String> cbxDiaPRM;
    private javax.swing.JComboBox<String> cbxMesPRM;
    private javax.swing.JComboBox<String> cbxNumeroGPRM;
    private javax.swing.JComboBox<String> cbxTipoGPRM;
    private javax.swing.JComboBox<String> cbxTipoPRM;
    private javax.swing.JComboBox<String> cbxdescripcionPRM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfClavePRM;
    private javax.swing.JTextField tfNoLotePRM;
    // End of variables declaration//GEN-END:variables
}
