/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.modificarP;

import controlador.ControladorProductoCongelado;
import javax.swing.JOptionPane;
import modelos.ProductoCongelado;

/**
 *
 * @author carol
 */
public class VentanaModificarPC extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaModificarPC
     */
    
    private ControladorProductoCongelado controlador = new ControladorProductoCongelado();
    
    public VentanaModificarPC() {
        initComponents();
        agregarCantidad();
        agregarNumGrados();
        agregarFecha();
    }
    
    private void agregarCantidad() {
        for (int i = 1; i <= 100; i++) {
            this.cbxCantidadPCM.addItem(Integer.toString(i));
        }
    }

    private void agregarNumGrados() {
        for (int i = -10; i <= 10; i++) {
            this.cbxNumeroGPCM.addItem(Integer.toString(i));
        }

        this.cbxNumeroGPCM.setSelectedItem("0");
    }

    private void agregarFecha() {
        for (int i = 1; i <= 31; i++) {
            this.cbxDiaPCM.addItem(Integer.toString(i));
        }
        for (int i = 2021; i < 2050; i++) {
            this.cbxAnioPCM.addItem(Integer.toString(i));
        }
    }

    private void limpiarObjetos() {
        String[] items = {"Selecciona", "contacto_directo", "por_aire", "criogénico"};
        this.tfClavePCM.setText("");
        this.cbxdescripcionPCM.setSelectedIndex(0);
        this.cbxCantidadPCM.setSelectedIndex(0);
        this.tfNoLotePCM.setText("");
        this.cbxDiaPCM.setSelectedIndex(0);
        this.cbxMesPCM.setSelectedIndex(0);
        this.cbxAnioPCM.setSelectedIndex(0);
        this.cbxNumeroGPCM.setSelectedItem("0");
        this.cbxTipoGPCM.setSelectedIndex(0);
        this.cbxTipoPCM.removeAllItems();
        for (String item : items){
            this.cbxTipoPCM.addItem(item);
        }
    }

    private void habilitarCampos() {
        this.cbxdescripcionPCM.setEnabled(true);
        this.cbxCantidadPCM.setEnabled(true);
        this.tfNoLotePCM.setEnabled(true);
        this.cbxDiaPCM.setEnabled(true);
        this.cbxMesPCM.setEnabled(true);
        this.cbxAnioPCM.setEnabled(true);
        this.cbxNumeroGPCM.setEnabled(true);
        this.cbxTipoGPCM.setEnabled(true);
        this.cbxTipoPCM.setEnabled(true);
        
        this.btnGuardarPCM.setEnabled(true);
        this.btnCancelarPCM.setEnabled(true);
    }

    private void desactivarCampos() {
        this.cbxdescripcionPCM.setEnabled(false);
        this.cbxCantidadPCM.setEnabled(false);
        this.tfNoLotePCM.setEnabled(false);
        this.cbxDiaPCM.setEnabled(false);
        this.cbxMesPCM.setEnabled(false);
        this.cbxAnioPCM.setEnabled(false);
        this.cbxNumeroGPCM.setEnabled(false);
        this.cbxTipoGPCM.setEnabled(false);
        this.cbxTipoPCM.setEnabled(false);
        this.btnGuardarPCM.setEnabled(false);
        this.btnCancelarPCM.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxTipoGPCM = new javax.swing.JComboBox<>();
        cbxCantidadPCM = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxDiaPCM = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxMesPCM = new javax.swing.JComboBox<>();
        cbxNumeroGPCM = new javax.swing.JComboBox<>();
        cbxTipoPCM = new javax.swing.JComboBox<>();
        cbxAnioPCM = new javax.swing.JComboBox<>();
        cbxdescripcionPCM = new javax.swing.JComboBox<>();
        btnBuscarPC = new javax.swing.JButton();
        btnGuardarPCM = new javax.swing.JButton();
        btnCancelarPCM = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfNoLotePCM = new javax.swing.JTextField();
        tfClavePCM = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Modificar producto congelado");

        cbxTipoGPCM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));
        cbxTipoGPCM.setEnabled(false);

        cbxCantidadPCM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        cbxCantidadPCM.setEnabled(false);
        cbxCantidadPCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantidadPCMActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad");

        cbxDiaPCM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día" }));
        cbxDiaPCM.setEnabled(false);

        jLabel3.setText("Temperatura recomendada");

        jLabel5.setText("Descripcion");

        jLabel7.setText("Tipo");

        cbxMesPCM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbxMesPCM.setEnabled(false);
        cbxMesPCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesPCMActionPerformed(evt);
            }
        });

        cbxNumeroGPCM.setEnabled(false);

        cbxTipoPCM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "contacto_directo", "por_aire", "criogénico" }));
        cbxTipoPCM.setEnabled(false);
        cbxTipoPCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoPCMActionPerformed(evt);
            }
        });

        cbxAnioPCM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        cbxAnioPCM.setEnabled(false);

        cbxdescripcionPCM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Marisco", "Carne", "Fruta", "Verdura", "Panaderia", "Lacteos" }));
        cbxdescripcionPCM.setEnabled(false);
        cbxdescripcionPCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxdescripcionPCMActionPerformed(evt);
            }
        });

        btnBuscarPC.setText("Buscar");
        btnBuscarPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPCActionPerformed(evt);
            }
        });

        btnGuardarPCM.setText("Guardar");
        btnGuardarPCM.setEnabled(false);
        btnGuardarPCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPCMActionPerformed(evt);
            }
        });

        btnCancelarPCM.setText("Cancelar");
        btnCancelarPCM.setEnabled(false);
        btnCancelarPCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPCMActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Clave");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("No. Lote");

        jLabel1.setText("Fecha de caducidad");

        tfNoLotePCM.setEnabled(false);
        tfNoLotePCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoLotePCMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbxNumeroGPCM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbxTipoGPCM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxTipoPCM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btnCancelarPCM)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnGuardarPCM))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbxDiaPCM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxMesPCM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxAnioPCM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfClavePCM, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(84, 84, 84)
                                    .addComponent(btnBuscarPC))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbxCantidadPCM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfNoLotePCM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(50, 50, 50)))
                    .addComponent(cbxdescripcionPCM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfClavePCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxdescripcionPCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxCantidadPCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNoLotePCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMesPCM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbxDiaPCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxAnioPCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxNumeroGPCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoGPCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxTipoPCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPCM)
                    .addComponent(btnCancelarPCM))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCantidadPCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantidadPCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCantidadPCMActionPerformed

    private void cbxMesPCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesPCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesPCMActionPerformed

    private void cbxdescripcionPCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxdescripcionPCMActionPerformed
       
    }//GEN-LAST:event_cbxdescripcionPCMActionPerformed

    private void btnBuscarPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPCActionPerformed
        if (!this.tfClavePCM.getText().equals("")) {

            if (this.controlador.validarClave(this.tfClavePCM.getText())) {

                ProductoCongelado producto = this.controlador.buscarProducto(this.tfClavePCM.getText());
                habilitarCampos();

                this.cbxdescripcionPCM.setSelectedItem(producto.getDescripcion());
                this.cbxCantidadPCM.setSelectedIndex(producto.getCantidad());

                String[] fecha = producto.getFechaCaducidad().split("/");
                this.cbxDiaPCM.setSelectedItem(fecha[0]);
                this.cbxMesPCM.setSelectedIndex(Integer.parseInt(fecha[1]));
                this.cbxAnioPCM.setSelectedItem(fecha[2]);

                String[] temperatura = producto.getTemperaturaRecomendada().split("/");
                this.cbxNumeroGPCM.setSelectedItem(temperatura[0]);
                this.cbxTipoGPCM.setSelectedItem(temperatura[1]);

                this.cbxTipoPCM.setSelectedItem(producto.getTipoCongelacion());
                this.tfNoLotePCM.setText(producto.getNumeroLote());

            } else {
                JOptionPane.showMessageDialog(null, "No se encontro ningun producto con esa clave");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Se necesita una clave par abuscar.");
        }
    }//GEN-LAST:event_btnBuscarPCActionPerformed

    private void btnGuardarPCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPCMActionPerformed
        ProductoCongelado nuevoProducto = new ProductoCongelado();
        controlador = new ControladorProductoCongelado();
        if (this.cbxdescripcionPCM.getSelectedIndex() != 0) {

            if (this.cbxCantidadPCM.getSelectedIndex() != 0) {

                if (!this.tfNoLotePCM.getText().equals("")) {

                    if (this.cbxDiaPCM.getSelectedIndex() != 0 || this.cbxMesPCM.getSelectedIndex() != 0 || this.cbxAnioPCM.getSelectedIndex() != 0) {

                        if (this.cbxTipoPCM.getSelectedIndex() != 0) {

                            nuevoProducto.setClave(this.tfClavePCM.getText());
                            nuevoProducto.setCantidad(Integer.parseInt(this.cbxCantidadPCM.getItemAt(this.cbxCantidadPCM.getSelectedIndex())));
                            nuevoProducto.setDescripcion(this.cbxdescripcionPCM.getItemAt(this.cbxdescripcionPCM.getSelectedIndex()));

                            String fecha = this.cbxDiaPCM.getItemAt(this.cbxDiaPCM.getSelectedIndex()) + "/"
                            + this.cbxMesPCM.getSelectedIndex() + "/"
                            + this.cbxAnioPCM.getItemAt(this.cbxAnioPCM.getSelectedIndex());

                            nuevoProducto.setFechaCaducidad(fecha);

                            String temp = this.cbxNumeroGPCM.getItemAt(this.cbxNumeroGPCM.getSelectedIndex()) + "/"
                            + this.cbxTipoGPCM.getItemAt(this.cbxTipoGPCM.getSelectedIndex());

                            nuevoProducto.setTemperaturaRecomendada(temp);

                            nuevoProducto.setTipoCongelacion(this.cbxTipoPCM.getItemAt(this.cbxTipoPCM.getSelectedIndex()));
                            nuevoProducto.setNumeroLote(this.tfNoLotePCM.getText());

                            limpiarObjetos();
                            desactivarCampos();
                            controlador.modificarProducto(nuevoProducto);
                        } else {
                            JOptionPane.showMessageDialog(null, "El producto debe de tener un tipo de alimento.");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Ingresa una fecha valida.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El producto debe de tener un número de lote.");
                }

            } else {
                JOptionPane.showMessageDialog(null, "La cantidad del producto debe de ser mayor a cero.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Es necesario seleccionar una descripcion\ndel producto.");
        }
    }//GEN-LAST:event_btnGuardarPCMActionPerformed

    private void btnCancelarPCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPCMActionPerformed
        limpiarObjetos();
        this.desactivarCampos();
        JOptionPane.showMessageDialog(null, "Operacion cancelada", "Modificar productos congelados", 2);
        this.dispose();
    }//GEN-LAST:event_btnCancelarPCMActionPerformed

    private void tfNoLotePCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoLotePCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoLotePCMActionPerformed

    private void cbxTipoPCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoPCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoPCMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPC;
    private javax.swing.JButton btnCancelarPCM;
    private javax.swing.JButton btnGuardarPCM;
    private javax.swing.JComboBox<String> cbxAnioPCM;
    private javax.swing.JComboBox<String> cbxCantidadPCM;
    private javax.swing.JComboBox<String> cbxDiaPCM;
    private javax.swing.JComboBox<String> cbxMesPCM;
    private javax.swing.JComboBox<String> cbxNumeroGPCM;
    private javax.swing.JComboBox<String> cbxTipoGPCM;
    private javax.swing.JComboBox<String> cbxTipoPCM;
    private javax.swing.JComboBox<String> cbxdescripcionPCM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfClavePCM;
    private javax.swing.JTextField tfNoLotePCM;
    // End of variables declaration//GEN-END:variables
}
