/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.listasP;

import controlador.ControladorProductoCongelado;
import javax.swing.table.DefaultTableModel;
import modelos.ProductoCongelado;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author carol
 */
public class VentanaListadoPC extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaListadoPC
     */
    public VentanaListadoPC() {
        initComponents();
        generarTable();
    }
    
    private void generarTable(){
        
        ControladorProductoCongelado controlador = new ControladorProductoCongelado();
        
        List<ProductoCongelado> listaProductos = controlador.mostrarTodoProductosF();
        
        DefaultTableModel modeloTabla = new DefaultTableModel(new String[]{"id", "Clave", "Descripción", "Cantidad", "No. Lote", "Fecha Cad.",
        "Temperatura Recom.", "Tipo de Congelación"}, 0);
        Object[] fila = new Object[modeloTabla.getColumnCount()];
        
        this.tablaProductosC.setModel(modeloTabla);
        
        if (listaProductos != null){
            
            if (!listaProductos.isEmpty()) {
                
                for (int i = 0; i<listaProductos.size(); i++){
                    
                    fila[0] = (i+1);
                    fila[1] = listaProductos.get(i).getClave();
                    fila[2] = listaProductos.get(i).getDescripcion();
                    fila[3] = listaProductos.get(i).getCantidad();
                    fila[4] = listaProductos.get(i).getNumeroLote();
                    fila[5] = listaProductos.get(i).getFechaCaducidad();
                    fila[6] = listaProductos.get(i).getTemperaturaRecomendada().replace("/", " ");
                    fila[7] = listaProductos.get(i).getTipoCongelacion();
                    
                    modeloTabla.addRow(fila);
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Lista vacia.\nNo se han encontrado registros.", "Lista productos congelados", 3);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Lista vacia.\nNo se han encontrado registros.", "Lista productos congelados", 3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductosC = new javax.swing.JTable();

        setClosable(true);
        setTitle("Listado productos congelados");

        tablaProductosC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Clave", "Descripción", "Cantidad", "No. Lote", "Fecha Cad.", "Temperatura Recom.", "Tipo de congelación"
            }
        ));
        jScrollPane1.setViewportView(tablaProductosC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductosC;
    // End of variables declaration//GEN-END:variables
}
