/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.agregarP;

import controlador.ControladorProductoCongelado;
import javax.swing.JOptionPane;
import modelos.ProductoCongelado;

/**
 *
 * @author carol
 */
public class VentanaProductoCongelado extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaNuevoProducto
     */
    public VentanaProductoCongelado() {
        initComponents();
        agregarCantidad();
        agregarFecha();
        agregarNumGrados();
    }

    private void agregarCantidad() {
        for (int i = 1; i <= 100; i++) {
            this.cbxCantidadPC.addItem(Integer.toString(i));
        }
    }

    private void agregarNumGrados() {
        for (int i = -10; i <= 10; i++) {
            this.cbxNumeroGPC.addItem(Integer.toString(i));
        }

        this.cbxNumeroGPC.setSelectedItem("0");
    }

    private void agregarFecha() {
        for (int i = 1; i <= 31; i++) {
            this.cbxDiaPC.addItem(Integer.toString(i));
        }
        for (int i = 2021; i < 2050; i++) {
            this.cbxAnioPC.addItem(Integer.toString(i));
        }
    }

    private void limpiarObjetos() {
        String[] items = {"Selecciona", "contacto_directo", "por_aire", "criogénico"};
        this.tfClavePC.setText("");
        this.cbxdescripcionPC.setSelectedIndex(0);
        this.cbxCantidadPC.setSelectedIndex(0);
        this.tfNoLotePC.setText("");
        this.cbxDiaPC.setSelectedIndex(0);
        this.cbxMesPC.setSelectedIndex(0);
        this.cbxAnioPC.setSelectedIndex(0);
        this.cbxNumeroGPC.setSelectedItem("0");
        this.cbxTipoGPC.setSelectedIndex(0);
        this.cbxTipoPC.removeAllItems();
        for (String item : items){
            this.cbxTipoPC.addItem(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxDiaPC = new javax.swing.JComboBox<>();
        cbxMesPC = new javax.swing.JComboBox<>();
        cbxAnioPC = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfNoLotePC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxNumeroGPC = new javax.swing.JComboBox<>();
        cbxTipoGPC = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfClavePC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxCantidadPC = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxTipoPC = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        cbxdescripcionPC = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Nuevo producto congelado");

        jLabel1.setText("Fecha de caducidad");

        cbxDiaPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día" }));

        cbxMesPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbxMesPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesPCActionPerformed(evt);
            }
        });

        cbxAnioPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("No. Lote");

        tfNoLotePC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoLotePCActionPerformed(evt);
            }
        });

        jLabel3.setText("Temperatura recomendada");

        cbxTipoGPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Clave");

        jLabel5.setText("Descripcion");

        jLabel6.setText("Cantidad");

        cbxCantidadPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        cbxCantidadPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantidadPCActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de congelación");

        cbxTipoPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "contacto_directo", "por_aire", "criogénico" }));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbxdescripcionPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Marisco", "Carne", "Fruta", "Verdura", "Panaderia", "Lacteos" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxCantidadPC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxDiaPC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMesPC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAnioPC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfClavePC, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNoLotePC, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxdescripcionPC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxNumeroGPC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoGPC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoPC, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfClavePC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbxdescripcionPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxCantidadPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNoLotePC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMesPC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbxDiaPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxAnioPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxNumeroGPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoGPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxTipoPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCantidadPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantidadPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCantidadPCActionPerformed

    private void cbxMesPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesPCActionPerformed

    private void tfNoLotePCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoLotePCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoLotePCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ProductoCongelado nuevoProducto = new ProductoCongelado();
        ControladorProductoCongelado controlador = new ControladorProductoCongelado();
        
        if (this.cbxdescripcionPC.getSelectedIndex() != 0) {

            if (this.cbxCantidadPC.getSelectedIndex() != 0) {

                if (!this.tfNoLotePC.getText().equals("")) {

                    if (this.cbxDiaPC.getSelectedIndex() != 0 || this.cbxMesPC.getSelectedIndex() != 0 || this.cbxAnioPC.getSelectedIndex() != 0) {

                        if (this.cbxTipoPC.getSelectedIndex() != 0) {

                            if (!controlador.validarClave(this.tfClavePC.getText())) {

                                nuevoProducto.setClave(this.tfClavePC.getText());
                                nuevoProducto.setCantidad(Integer.parseInt(this.cbxCantidadPC.getItemAt(this.cbxCantidadPC.getSelectedIndex())));
                                nuevoProducto.setDescripcion(this.cbxdescripcionPC.getItemAt(this.cbxdescripcionPC.getSelectedIndex()));

                                String fecha = this.cbxDiaPC.getItemAt(this.cbxDiaPC.getSelectedIndex()) + "/"
                                        + this.cbxMesPC.getSelectedIndex() + "/"
                                        + this.cbxAnioPC.getItemAt(this.cbxAnioPC.getSelectedIndex());

                                nuevoProducto.setFechaCaducidad(fecha);

                                String temp = this.cbxNumeroGPC.getItemAt(this.cbxNumeroGPC.getSelectedIndex()) + "/"
                                        + this.cbxTipoGPC.getItemAt(this.cbxTipoGPC.getSelectedIndex());

                                nuevoProducto.setTemperaturaRecomendada(temp);

                                nuevoProducto.setTipoCongelacion(this.cbxTipoPC.getItemAt(this.cbxTipoPC.getSelectedIndex()));
                                nuevoProducto.setNumeroLote(this.tfNoLotePC.getText());

                                limpiarObjetos();
                                controlador.agregarProducto(nuevoProducto);
                            } else {
                                JOptionPane.showMessageDialog(null, "La clave " + this.tfClavePC.getText() + "\nYa se encuentra registrada", "Agregar producto fresco", 2);
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "El producto debe de tener un tipo de alimento.");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Ingresa una fecha valida.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El producto debe de tener un número de lote.");
                }

            } else {
                JOptionPane.showMessageDialog(null, "La cantidad del producto debe de ser mayor a cero.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Es necesario seleccionar una descripcion\ndel producto.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiarObjetos();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAnioPC;
    private javax.swing.JComboBox<String> cbxCantidadPC;
    private javax.swing.JComboBox<String> cbxDiaPC;
    private javax.swing.JComboBox<String> cbxMesPC;
    private javax.swing.JComboBox<String> cbxNumeroGPC;
    private javax.swing.JComboBox<String> cbxTipoGPC;
    private javax.swing.JComboBox<String> cbxTipoPC;
    private javax.swing.JComboBox<String> cbxdescripcionPC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfClavePC;
    private javax.swing.JTextField tfNoLotePC;
    // End of variables declaration//GEN-END:variables
}
