/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.agregarP;

import controlador.ControladorProductoFresco;
import javax.swing.JOptionPane;
import modelos.ProductoFresco;

/**
 *
 * @author carol
 */
public class VentanaProductoFresco extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaProductoFresco
     */
    private final String[] carne = {"Selecciona", "Ternera", "Res", "Puerco", "Cordero", "Lechon"};
    private final String[] lacteo = {"Selecciona", "Leche", "Mantequilla", "Queso", "Yogurt"};
    private final String[] marisco = {"Selcciona", "Mero", "Atun", "Bacalao", "Carpa", "Salmon", "Trucha", "Sardina"};
    private final String[] fruta = {"Selecciona", "Manzana", "Platano", "Pera", "Naranja"};
    private final String[] verdura = {"Selecciona", "Lechuga", "Apio", "Repollo", "Zanahoria", "Cebolla"};
    private final String[] panaderia = {"Selecciona", "Pan frances", "Pan de centeno", "Bagels", "Croissant"};

    public VentanaProductoFresco() {
        initComponents();
        agregarCantidad();
        agregarFecha();
        agregarNumGrados();
    }

    private void agregarCantidad() {
        for (int i = 1; i <= 100; i++) {
            this.cbxCantidadPF.addItem(Integer.toString(i));
        }
    }

    private void agregarNumGrados() {
        for (int i = -10; i <= 10; i++) {
            this.cbxNumeroGPF.addItem(Integer.toString(i));
        }

        this.cbxNumeroGPF.setSelectedItem("0");
    }

    private void agregarFecha() {
        for (int i = 1; i <= 31; i++) {
            this.cbxDiaPF.addItem(Integer.toString(i));
        }
        for (int i = 2021; i < 2050; i++) {
            this.cbxAnioPF.addItem(Integer.toString(i));
        }
    }

    private void limpiarObjetos() {
        this.tfClavePF.setText("");
        this.cbxdescripcionPF.setSelectedIndex(0);
        this.cbxCantidadPF.setSelectedIndex(0);
        this.tfNoLotePF.setText("");
        this.cbxDiaPF.setSelectedIndex(0);
        this.cbxMesPF.setSelectedIndex(0);
        this.cbxAnioPF.setSelectedIndex(0);
        this.cbxNumeroGPF.setSelectedItem("0");
        this.cbxTipoGPF.setSelectedIndex(0);
        this.cbxTipoPF.removeAllItems();
        this.cbxTipoPF.addItem("Selecciona");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfNoLotePF = new javax.swing.JTextField();
        cbxCantidadPF = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxNumeroGPF = new javax.swing.JComboBox<>();
        cbxTipoGPF = new javax.swing.JComboBox<>();
        cbxTipoPF = new javax.swing.JComboBox<>();
        btnGuardarPF = new javax.swing.JButton();
        btnCancelarPF = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfClavePF = new javax.swing.JTextField();
        cbxDiaPF = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxMesPF = new javax.swing.JComboBox<>();
        cbxAnioPF = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxdescripcionPF = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Nuevo producto fresco");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("No. Lote");

        tfNoLotePF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoLotePFActionPerformed(evt);
            }
        });

        cbxCantidadPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        cbxCantidadPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantidadPFActionPerformed(evt);
            }
        });

        jLabel3.setText("Temperatura recomendada");

        jLabel7.setText("Tipo");

        cbxTipoGPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));

        cbxTipoPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));

        btnGuardarPF.setText("Guardar");
        btnGuardarPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPFActionPerformed(evt);
            }
        });

        btnCancelarPF.setText("Cancelar");
        btnCancelarPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPFActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Clave");

        jLabel1.setText("Fecha de caducidad");

        cbxDiaPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día" }));

        jLabel5.setText("Descripcion");

        cbxMesPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbxMesPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesPFActionPerformed(evt);
            }
        });

        cbxAnioPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));

        jLabel6.setText("Cantidad");

        cbxdescripcionPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Marisco", "Carne", "Fruta", "Verdura", "Panaderia", "Lacteos" }));
        cbxdescripcionPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxdescripcionPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelarPF)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarPF))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxCantidadPF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxDiaPF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMesPF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAnioPF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfClavePF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNoLotePF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxdescripcionPF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxNumeroGPF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoGPF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxTipoPF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfClavePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbxdescripcionPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxCantidadPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNoLotePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMesPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbxDiaPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxAnioPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxNumeroGPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoGPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxTipoPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPF)
                    .addComponent(btnCancelarPF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNoLotePFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoLotePFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoLotePFActionPerformed

    private void cbxCantidadPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantidadPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCantidadPFActionPerformed

    private void cbxMesPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesPFActionPerformed

    private void btnGuardarPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPFActionPerformed
        ProductoFresco nuevoProducto = new ProductoFresco();
        ControladorProductoFresco controlador = new ControladorProductoFresco();
        if (this.cbxdescripcionPF.getSelectedIndex() != 0) {

            if (this.cbxCantidadPF.getSelectedIndex() != 0) {

                if (!this.tfNoLotePF.getText().equals("")) {

                    if (this.cbxDiaPF.getSelectedIndex() != 0 || this.cbxMesPF.getSelectedIndex() != 0 || this.cbxAnioPF.getSelectedIndex() != 0) {

                        if (this.cbxTipoPF.getSelectedIndex() != 0) {

                            if (!controlador.validarClave(this.tfClavePF.getText())) {
                                
                                nuevoProducto.setClave(this.tfClavePF.getText());
                                nuevoProducto.setCantidad(Integer.parseInt(this.cbxCantidadPF.getItemAt(this.cbxCantidadPF.getSelectedIndex())));
                                nuevoProducto.setDescripcion(this.cbxdescripcionPF.getItemAt(this.cbxdescripcionPF.getSelectedIndex()));

                                String fecha = this.cbxDiaPF.getItemAt(this.cbxDiaPF.getSelectedIndex()) + "/"
                                        + this.cbxMesPF.getSelectedIndex() + "/"
                                        + this.cbxAnioPF.getItemAt(this.cbxAnioPF.getSelectedIndex());

                                nuevoProducto.setFechaCaducidad(fecha);

                                String temp = this.cbxNumeroGPF.getItemAt(this.cbxNumeroGPF.getSelectedIndex()) + "/"
                                        + this.cbxTipoGPF.getItemAt(this.cbxTipoGPF.getSelectedIndex());

                                nuevoProducto.setTemperaturaRecomendada(temp);

                                nuevoProducto.setTipoAlimento(this.cbxTipoPF.getItemAt(this.cbxTipoPF.getSelectedIndex()));
                                nuevoProducto.setNumeroLote(this.tfNoLotePF.getText());

                                limpiarObjetos();
                                controlador.agregarProducto(nuevoProducto);
                            }else{
                                JOptionPane.showMessageDialog(null, "La clave "+this.tfClavePF.getText()+"\nYa se encuentra registrada", "Agregar producto fresco", 2);
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "El producto debe de tener un tipo de alimento.");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Ingresa una fecha valida.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El producto debe de tener un número de lote.");
                }

            } else {
                JOptionPane.showMessageDialog(null, "La cantidad del producto debe de ser mayor a cero.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Es necesario seleccionar una descripcion\ndel producto.");
        }
    }//GEN-LAST:event_btnGuardarPFActionPerformed

    private void cbxdescripcionPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxdescripcionPFActionPerformed
        switch (this.cbxdescripcionPF.getSelectedIndex()) {
            case 1:
                this.cbxTipoPF.removeAllItems();
                for (String item : marisco) {
                    this.cbxTipoPF.addItem(item);
                }
                break;
            case 2:
                this.cbxTipoPF.removeAllItems();
                for (String item : carne) {
                    this.cbxTipoPF.addItem(item);
                }
                break;
            case 3:
                this.cbxTipoPF.removeAllItems();
                for (String item : fruta) {
                    this.cbxTipoPF.addItem(item);
                }
                break;
            case 4:
                this.cbxTipoPF.removeAllItems();
                for (String item : verdura) {
                    this.cbxTipoPF.addItem(item);
                }
                break;
            case 5:
                this.cbxTipoPF.removeAllItems();
                for (String item : panaderia) {
                    this.cbxTipoPF.addItem(item);
                }
                break;
            case 6:
                this.cbxTipoPF.removeAllItems();
                for (String item : lacteo) {
                    this.cbxTipoPF.addItem(item);
                }
                break;
        }
    }//GEN-LAST:event_cbxdescripcionPFActionPerformed

    private void btnCancelarPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPFActionPerformed
        limpiarObjetos();
        this.dispose();
    }//GEN-LAST:event_btnCancelarPFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPF;
    private javax.swing.JButton btnGuardarPF;
    private javax.swing.JComboBox<String> cbxAnioPF;
    private javax.swing.JComboBox<String> cbxCantidadPF;
    private javax.swing.JComboBox<String> cbxDiaPF;
    private javax.swing.JComboBox<String> cbxMesPF;
    private javax.swing.JComboBox<String> cbxNumeroGPF;
    private javax.swing.JComboBox<String> cbxTipoGPF;
    private javax.swing.JComboBox<String> cbxTipoPF;
    private javax.swing.JComboBox<String> cbxdescripcionPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfClavePF;
    private javax.swing.JTextField tfNoLotePF;
    // End of variables declaration//GEN-END:variables
}
