/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.agregarP;

import controlador.ControladorProductoRefrigerado;
import javax.swing.JOptionPane;
import modelos.ProductoRefrigerado;

/**
 *
 * @author carol
 */
public class VentanaProductoRefrigerado extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaProductoRefrigerado
     */
   
    public VentanaProductoRefrigerado() {
        initComponents();
        agregarCantidad();
        agregarFecha();
        agregarNumGrados();
    }
    
    private void agregarCantidad() {
        for (int i = 1; i <= 100; i++) {
            this.cbxCantidadPR.addItem(Integer.toString(i));
        }
    }

    private void agregarNumGrados() {
        for (int i = -10; i <= 10; i++) {
            this.cbxNumeroGPR.addItem(Integer.toString(i));
        }

        this.cbxNumeroGPR.setSelectedItem("0");
    }

    private void agregarFecha() {
        for (int i = 1; i <= 31; i++) {
            this.cbxDiaPR.addItem(Integer.toString(i));
        }
        for (int i = 2021; i < 2050; i++) {
            this.cbxAnioPR.addItem(Integer.toString(i));
        }
    }

    private void limpiarObjetos() {
        this.tfClavePR.setText("");
        this.cbxdescripcionPR.setSelectedIndex(0);
        this.cbxCantidadPR.setSelectedIndex(0);
        this.tfNumeroLotePR.setText("");
        this.cbxDiaPR.setSelectedIndex(0);
        this.cbxMesPR.setSelectedIndex(0);
        this.cbxAnioPR.setSelectedIndex(0);
        this.cbxNumeroGPR.setSelectedItem("0");
        this.cbxTipoGPR.setSelectedIndex(0);
        this.cbxTipoPR.removeAllItems();
        this.cbxTipoPR.addItem("Selecciona");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        cbxMesPR = new javax.swing.JComboBox<>();
        cbxNumeroGPR = new javax.swing.JComboBox<>();
        cbxTipoGPR = new javax.swing.JComboBox<>();
        cbxAnioPR = new javax.swing.JComboBox<>();
        cbxTipoPR = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnGuardarPR = new javax.swing.JButton();
        cbxdescripcionPR = new javax.swing.JComboBox<>();
        btnCancelarPR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfNumeroLotePR = new javax.swing.JTextField();
        tfClavePR = new javax.swing.JTextField();
        cbxCantidadPR = new javax.swing.JComboBox<>();
        cbxDiaPR = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Nuevo producto refrigerado");

        jLabel7.setText("Tipo de contaminacion");

        cbxMesPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbxMesPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesPRActionPerformed(evt);
            }
        });

        cbxTipoGPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));

        cbxAnioPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));

        cbxTipoPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Fisico", "Quimico", "Biologicos", "Microbiologicos" }));

        jLabel6.setText("Cantidad");

        btnGuardarPR.setText("Guardar");
        btnGuardarPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPRActionPerformed(evt);
            }
        });

        cbxdescripcionPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Marisco", "Carne", "Fruta", "Verdura", "Panaderia", "Lacteos" }));

        btnCancelarPR.setText("Cancelar");
        btnCancelarPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPRActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Clave");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("No. Lote");

        jLabel1.setText("Fecha de caducidad");

        tfNumeroLotePR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroLotePRActionPerformed(evt);
            }
        });

        cbxCantidadPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        cbxCantidadPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantidadPRActionPerformed(evt);
            }
        });

        cbxDiaPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día" }));

        jLabel3.setText("Temperatura recomendada");

        jLabel5.setText("Descripcion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelarPR)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarPR))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxCantidadPR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxDiaPR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMesPR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAnioPR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfClavePR, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNumeroLotePR, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxdescripcionPR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxNumeroGPR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoGPR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxTipoPR, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfClavePR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbxdescripcionPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxCantidadPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNumeroLotePR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMesPR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbxDiaPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxAnioPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxNumeroGPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoGPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxTipoPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPR)
                    .addComponent(btnCancelarPR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxMesPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesPRActionPerformed

    private void tfNumeroLotePRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroLotePRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroLotePRActionPerformed

    private void cbxCantidadPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantidadPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCantidadPRActionPerformed

    private void btnGuardarPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPRActionPerformed
        ProductoRefrigerado nuevoProducto = new ProductoRefrigerado();
        ControladorProductoRefrigerado controlador = new ControladorProductoRefrigerado();
        
        if (this.cbxdescripcionPR.getSelectedIndex() != 0) {

            if (this.cbxCantidadPR.getSelectedIndex() != 0) {

                if (!this.tfNumeroLotePR.getText().equals("")) {

                    if (this.cbxDiaPR.getSelectedIndex() != 0 || this.cbxMesPR.getSelectedIndex() != 0 || this.cbxAnioPR.getSelectedIndex() != 0) {

                        if (this.cbxTipoPR.getSelectedIndex() != 0) {

                            if (!controlador.validarClave(this.tfClavePR.getText())) {
                                
                                nuevoProducto.setClave(this.tfClavePR.getText());
                                nuevoProducto.setCantidad(Integer.parseInt(this.cbxCantidadPR.getItemAt(this.cbxCantidadPR.getSelectedIndex())));
                                nuevoProducto.setDescripcion(this.cbxdescripcionPR.getItemAt(this.cbxdescripcionPR.getSelectedIndex()));

                                String fecha = this.cbxDiaPR.getItemAt(this.cbxDiaPR.getSelectedIndex()) + "/"
                                        + this.cbxMesPR.getSelectedIndex() + "/"
                                        + this.cbxAnioPR.getItemAt(this.cbxAnioPR.getSelectedIndex());

                                nuevoProducto.setFechaCaducidad(fecha);

                                String temp = this.cbxNumeroGPR.getItemAt(this.cbxNumeroGPR.getSelectedIndex()) + "/"
                                        + this.cbxTipoGPR.getItemAt(this.cbxTipoGPR.getSelectedIndex());

                                nuevoProducto.setTemperaturaRecomendada(temp);

                                nuevoProducto.setTipoContaminacion(this.cbxTipoPR.getItemAt(this.cbxTipoPR.getSelectedIndex()));
                                nuevoProducto.setNumeroLote(this.tfNumeroLotePR.getText());

                                limpiarObjetos();
                                controlador.agregarProducto(nuevoProducto);
                            }else{
                                JOptionPane.showMessageDialog(null, "La clave "+this.tfClavePR.getText()+"\nYa se encuentra registrada", "Agregar producto fresco", 2);
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "El producto debe de tener un tipo de alimento.");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Ingresa una fecha valida.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El producto debe de tener un número de lote.");
                }

            } else {
                JOptionPane.showMessageDialog(null, "La cantidad del producto debe de ser mayor a cero.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Es necesario seleccionar una descripcion\ndel producto.");
        }
    }//GEN-LAST:event_btnGuardarPRActionPerformed

    private void btnCancelarPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPRActionPerformed
        limpiarObjetos();
        this.dispose();
    }//GEN-LAST:event_btnCancelarPRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPR;
    private javax.swing.JButton btnGuardarPR;
    private javax.swing.JComboBox<String> cbxAnioPR;
    private javax.swing.JComboBox<String> cbxCantidadPR;
    private javax.swing.JComboBox<String> cbxDiaPR;
    private javax.swing.JComboBox<String> cbxMesPR;
    private javax.swing.JComboBox<String> cbxNumeroGPR;
    private javax.swing.JComboBox<String> cbxTipoGPR;
    private javax.swing.JComboBox<String> cbxTipoPR;
    private javax.swing.JComboBox<String> cbxdescripcionPR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfClavePR;
    private javax.swing.JTextField tfNumeroLotePR;
    // End of variables declaration//GEN-END:variables
}
